language: python
env:
  global:
  - STATE=initial
  - PACKAGE_UNDER_TEST=.
  - DEPLOYMENT_TOKEN_FILE=.i.am.the.master.deployer
python:
- '2.7'
- pypy
install:
- rvm install ruby-2.3.0
- rvm --default use 2.3.0
- npm install --save-dev travis-after-all
- gem install travis-yaml
- echo SHOULD INSTALL $PACKAGE_UNDER_TEST
- scripts/env.sh "  install  "
script:
- echo "test"
- ruby scripts/travis.env.rb HAHA=HOHO
- python -c 'import sys; print(sys.version); sys.exit(int(sys.version_info[:3] < (2,7,6)
  or (3,4,0) < sys.version_info[:3]))'
- [[ "$STATE" != "dev-stage-1" ]]
- scripts/env.sh "  script  "
- "$(npm bin)/travis-after-all && touch $DEPLOYMENT_TOKEN_FILE || rm -f $DEPLOYMENT_TOKEN_FILE"
before_deploy:
- echo "before_deploy"
- echo "hello as of $(date)" > hello.txt
- env | sort | awk '{print "after_deploy", $0}'
deploy:
- provider: script
  on:
    condition: ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "initial" )
    repo: bozzzzo/sandbox
    branch: master
    tags: false
  script: scripts/respawn.sh STATE=dev-stage-1 PACKAGE_UNDER_TEST=datawire-quarkdev
  skip_cleanup: true
- provider: script
  on:
    condition: ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "dev-stage-1" )
    repo: bozzzzo/sandbox
    branch: master
    tags: false
  script: scripts/respawn.sh STATE=dev-stage-2 PACKAGE_UNDER_TEST="what-if-I-dont-want-any..."
  skip_cleanup: true
- provider: releases
  api_key:
    secure: QUbnJncuzOHqOYXc6TdZFwoYK+S4jhroGBZvqRX+ZDCEtdZlqx+lAnV9Zu8xxEAtEq+4X0OgN6wtMlbIus2jkHJL9yny2Jhh1J55c8sQg2Q3IdIestodvxryIr9McVaTg3rW9p9sgHS5qRZmbeKqcXOnMNNiXLXTwxOU+/C70UwrsXpNtERj5zp4/88rSR4K5zX7IhFyI7tdbkJDTj6A119KMQ+t0HdEmXaE9sKQm0PNI1jujrkrsuqQkdJiYxWh78tQxakVfMuRdPrd7knwNbcNUvFUtt5R48IxTJ3O5VwkQZbmUKBtXjXeC5bDxBPLlFsxJhfhDiBM+4o1prqe7in3l9n62DkV+xQdBL1gfzTyaILZ5OO68HuguCsWqx+G5eApjPLeLUCR3dhYEP8uwXY3xJdSrgDCDbWTpP4XXxDuIbVkFpeFqJ7efmlUi+HEJfyht5vUlNt0BjNG3M/lXTfEueprycXZL9G8h6jsUuNPXTC2FSVm4lbNkFeXRFSe2mNyD8QVaxMJDr4at/+e+G483OYqABNw3ypRuoLQ682Lryov2BMD52RD7wvU+V1Rtfx/Sh1q7Wd4qvJN5EXdDXWtqh+f1xp+RCuSuPHmnvObeH7Jj9/Vt7I1BdX91pyxcI3jGDVscvBX4dnjmCeFltpF9oKXcGc0Q2zNNhMuYUM=
  file: hello.txt
  skip_cleanup: true
  on:
    repo: bozzzzo/sandbox
    branch: master
    tags: true
    condition: ( -f "$DEPLOYMENT_TOKEN_FILE") && ( "$STATE" = release-dev )
before_install:
- openssl aes-256-cbc -K $encrypted_4ff86a789e60_key -iv $encrypted_4ff86a789e60_iv
  -in .respawn.token.enc -out .respawn.token -d
