language: python
env:
  matrix:
  - DEPLOYMENT_TOKEN_FILE=.i.am.the.master.deployer
  global:
    secure: BznfOISy4UpH1MKw4Foz4z89RMkBw8Vb1yThl7XCGM9bpjVIGiTqISKaU0nswmFHyEXTYoC/iKrHFuwUa/GVPl7e25k6eY0KQtCgaaox0JqhrlMc00anA4dOash/S0p9l9g1VnOiA24cGGnLUuiHBAdPB046dcgeXcXxLO+fn5RmQ45ftjyHpPUWrA2HOGky4nC37zeQVWzfwFggvvvVHkSeiF0pS+PGoDNskqGLc+yE5mbADY2fBYELPdEcM5OzLgVPqkmhQAtzBBVQ2sy1iNTFxgIzV1hD2hpF+2JBuST00Ba4cHkdiAoSwiKe1u8eTy7e0Yqsa/zqmoqDO1SWFa0jzpw/ieOPXNRBcb5HxiMKSkGY9vQKB2LSJ9UJfvTTwX7PZvwvbRHuG08d0BdjS5DPbit4q6VVn0Gdu5AwxhDz+VDeo9cx3GN7PY5E3iQODSTiyhC4WFmV6QHsoPrEl0IwMITCwozkIxFKf+JLhlXrXnhdg5xzKG1/ki01Fd7wvfpfMEX26SjtIGFJ3WOcdYX/VJVqblCzpOZeX/CDJFFq3GuN1X5+ICjW6bjeRVi/u2bjJYX8mrbyMzWq23ITKyQUkVt/H/YnGLgC5yWZ9TkPBFXGZ0t+fEsB7fe5owefj0Ci/ppdOuVPdqNmRZN2/rpUJfXz0Jvrb6OO0IwrIE8=
python:
- '2.7'
- '3.3'
- pypy
install:
- echo "install"
- env | sort | awk '{print "install", $0}'
- npm install --save-dev travis-after-all
script:
- echo "test"
- python -c 'import sys; print(sys.version); sys.exit(int(sys.version_info[:3] < (2,7,6)
  or (3,4,0) < sys.version_info[:3]))'
- echo $REBUILD_TOKEN | wc -l
- env | sort | awk '{print "script", $0}'
- "$(npm bin)/travis-after-all && touch $DEPLOYMENT_TOKEN_FILE || rm -f $DEPLOYMENT_TOKEN_FILE"
after_script:
- echo "after_script"
before_deploy:
- echo "before_deploy"
- echo "hello as of $(date)" > hello.txt
- env | sort | awk '{print "after_deploy", $0}'
deploy:
- provider: releases
  api_key:
    secure: QUbnJncuzOHqOYXc6TdZFwoYK+S4jhroGBZvqRX+ZDCEtdZlqx+lAnV9Zu8xxEAtEq+4X0OgN6wtMlbIus2jkHJL9yny2Jhh1J55c8sQg2Q3IdIestodvxryIr9McVaTg3rW9p9sgHS5qRZmbeKqcXOnMNNiXLXTwxOU+/C70UwrsXpNtERj5zp4/88rSR4K5zX7IhFyI7tdbkJDTj6A119KMQ+t0HdEmXaE9sKQm0PNI1jujrkrsuqQkdJiYxWh78tQxakVfMuRdPrd7knwNbcNUvFUtt5R48IxTJ3O5VwkQZbmUKBtXjXeC5bDxBPLlFsxJhfhDiBM+4o1prqe7in3l9n62DkV+xQdBL1gfzTyaILZ5OO68HuguCsWqx+G5eApjPLeLUCR3dhYEP8uwXY3xJdSrgDCDbWTpP4XXxDuIbVkFpeFqJ7efmlUi+HEJfyht5vUlNt0BjNG3M/lXTfEueprycXZL9G8h6jsUuNPXTC2FSVm4lbNkFeXRFSe2mNyD8QVaxMJDr4at/+e+G483OYqABNw3ypRuoLQ682Lryov2BMD52RD7wvU+V1Rtfx/Sh1q7Wd4qvJN5EXdDXWtqh+f1xp+RCuSuPHmnvObeH7Jj9/Vt7I1BdX91pyxcI3jGDVscvBX4dnjmCeFltpF9oKXcGc0Q2zNNhMuYUM=
  file: hello.txt
  skip_cleanup: true
  on:
    repo: bozzzzo/sandbox
    branch: master
    tags: true
    condition: "-f $DEPLOYMENT_TOKEN_FILE"
- provider: script
  script: scripts/deployme.sh
  on:
    repo: bozzzzo/sandbox
    branch: master
    tags: false
    condition: "-f $DEPLOYMENT_TOKEN_FILE"
