language: python
env:
  matrix:
  - DEPLOYMENT_TOKEN_FILE=.i.am.the.master.deployer
  global:
  - secure: VZ6req7grSJyPmAO5aEYpfQQhDk9W2iv/NBTVx7uX54SjgYxLujKejxvGamyBi4NS/CIXa+xcOdGvWeFZqCmPp8Gy5gLqy7UUqk46jEHhvjVGdJSwafCRCAFHIHdnphWm7HwiuJ/KcC30r2cuLlffaDmUegmQgwYo9R5PF+t74PGAJDwFmkfi/BcPPiUGalzUX1dXHjzD2LLbojbyvElC26PRL/gWjGCpmZm97nbTuIi1fLFAoQ0I7zicHoFdVt5Pru9UwR0o0NZgGo7Q9vvMpJ7tWUc6rq5z3ZkvIcIpYAkld1HEm62fqD2Sz0xYcjzm9/pKlUsCinYSRq9QbUEX6cPMAAcfdYXYDxu0h0PEJOcksdx8cKsZCOd3LTltz3P9uiudRtladSJxcSfe/RnzMTU3Al1O8Fp/5HNHb07RCJc+m1e46KxjpUgguGmm381Om5c0VI/UGr/f2iiBsLBQHauzHriB/YSw9sFXFRrZX+UQkzYwIDq2Olv+vplDYQg3z1hOW4bWDZsr7kK/94ZTnP+0EPgNvH8zjf/fxaTndA091QoLAjIoeSx1rWSGCWP38+E5vhUJNS85v94QhAGliYNlVvVxkX2v+GDUWiYpokXR5hCBYleUJW2Q3kacPusj3GrXDhzGfUdSlVuvWLQs7w7iyKHLOS8F3iazWCBIEg=
  - secure: YvpRfpiK8XHmkHpQKBvvVT3alHG6WqcZSnhVFjyFkjGYSfBjLCwUC3+apLigb6sn/GvhYsBrGTbfIOtDKFiPFiXIATmVbbB1Uqff7ktS5llROiX64LacVe837id/MiAV6SibUm6siU0cNRpAI2t3wrfG90P8dI6DvQ/ZMwuMbhyUygmdvt/ONIny4OGTGZBM1MPM0/dNxTT2shthDPIUjDAe3JjKaz0xNTnauHmEA9jMhk1386vSBm/HGy/m4R4b/ld+6ag8lEhEbM6D+iMv8HVYPdyOyZORz7XUEvAdwgeWmbU3ah/bNpne4HJWokuSPJ9UN/5r5mFXts0SnvZVa09S7qtOMcru9VIeLTSpX2sd+lZ93FemEng+wQEtxOHJP4A6/y1i32TIo2WOYl9Wjk0qFAwz6P9ObdFpFgYi3UZYi+A20pC/p54nDvOyXeCC2+BB8BTIIDSMPBu1cgwAFNwXivq+fnEMufnVpF2cYAP2uoB017ERki7ANHrBTr7XMNJL/kYejKqj7fcyd+3cwIY29FGOa5oB2nPt4REZYdvhToZpDJOh6Q5+9ZpUU8xvZH3UkC7KXFbascdccaH9myGV1vI4NCnoUIHyRy7QX2TFIVc4QXH1RMAxnNgRyy0mI2efCviRdwb4bAsFxJfsfSs4Dqg+0t4oZiIh/GEOZv4=
python:
- '2.7'
- '3.3'
- pypy
install:
- echo "install"
- env | sort | awk '{print "install", $0}'
- npm install --save-dev travis-after-all
script:
- echo "test"
- python -c 'import sys; print(sys.version); sys.exit(int(sys.version_info[:3] < (2,7,6)
  or (3,4,0) < sys.version_info[:3]))'
- env | sort | awk '{print "script", $0}'
- "$(npm bin)/travis-after-all && touch $DEPLOYMENT_TOKEN_FILE || rm -f $DEPLOYMENT_TOKEN_FILE"
after_script:
- echo "after_script"
before_deploy:
- echo "before_deploy"
- echo "hello as of $(date)" > hello.txt
- env | sort | awk '{print "after_deploy", $0}'
deploy:
  provider: releases
  api_key:
    secure: QUbnJncuzOHqOYXc6TdZFwoYK+S4jhroGBZvqRX+ZDCEtdZlqx+lAnV9Zu8xxEAtEq+4X0OgN6wtMlbIus2jkHJL9yny2Jhh1J55c8sQg2Q3IdIestodvxryIr9McVaTg3rW9p9sgHS5qRZmbeKqcXOnMNNiXLXTwxOU+/C70UwrsXpNtERj5zp4/88rSR4K5zX7IhFyI7tdbkJDTj6A119KMQ+t0HdEmXaE9sKQm0PNI1jujrkrsuqQkdJiYxWh78tQxakVfMuRdPrd7knwNbcNUvFUtt5R48IxTJ3O5VwkQZbmUKBtXjXeC5bDxBPLlFsxJhfhDiBM+4o1prqe7in3l9n62DkV+xQdBL1gfzTyaILZ5OO68HuguCsWqx+G5eApjPLeLUCR3dhYEP8uwXY3xJdSrgDCDbWTpP4XXxDuIbVkFpeFqJ7efmlUi+HEJfyht5vUlNt0BjNG3M/lXTfEueprycXZL9G8h6jsUuNPXTC2FSVm4lbNkFeXRFSe2mNyD8QVaxMJDr4at/+e+G483OYqABNw3ypRuoLQ682Lryov2BMD52RD7wvU+V1Rtfx/Sh1q7Wd4qvJN5EXdDXWtqh+f1xp+RCuSuPHmnvObeH7Jj9/Vt7I1BdX91pyxcI3jGDVscvBX4dnjmCeFltpF9oKXcGc0Q2zNNhMuYUM=
  file: hello.txt
  skip_cleanup: true
  on:
    repo: bozzzzo/sandbox
    branch: master
    tags: true
    condition: "-f $DEPLOYMENT_TOKEN_FILE"
